// Package store is the database layer. Its Go files are GENERATED by sqlc from
// the SQL you write in store/queries/*.sql — do not hand-edit them, and do not
// commit fights with the generator.
//
// EXERCISE (M1)
// -------------
//
//  1. Design the schema in api/migrations (see 00001_init.sql).
//
//  2. Write queries in store/queries/*.sql with sqlc annotations:
//
//     -- name: GetUserByEmail :one
//     SELECT * FROM users WHERE email = $1;
//
//  3. Run `make sqlc`. Type-safe Go appears here.
//
// Why this rather than an ORM: you write the SQL, so you can read the query plan,
// and the compiler checks the Go. When M5 asks you to kill an N+1 you will be
// editing a query, not fighting a query builder.
//
// Suggested files: users.sql, profiles.sql, articles.sql, comments.sql, tags.sql,
// favorites.sql.
package store
