// Package handler contains one HTTP handler per Conduit endpoint.
//
// Every method below is a stub that returns 501. The doc comment above each one
// is its contract, taken from the RealWorld spec, together with the Hurl file
// that will tell you when you have it right. Work top to bottom through
// LEARNING.md; do not try to do them all at once.
//
// Rule of thumb for what belongs here: decode the request, call one thing, encode
// the response. If a handler is growing branches and business rules, that logic
// wants to live in internal/domain (or a service type) instead.
package handler

import "net/http"

// Handler carries everything the endpoints need.
//
// TODO(M2): give this real dependencies, e.g.
//
//	type Handler struct {
//	    Store  *store.Queries   // generated by sqlc
//	    Auth   *auth.Tokens
//	    Logger *slog.Logger
//	}
//
// Construct it once in main.go and pass it to your router. Resist the urge to
// reach for package-level globals — they are what makes code untestable.
type Handler struct{}

// New returns a Handler. Extend the signature as you add dependencies.
func New() *Handler { return &Handler{} }

// todo is the placeholder every unimplemented endpoint returns. Delete it once
// the last stub is gone — that deletion is the finish line for the backend.
func todo(w http.ResponseWriter, _ *http.Request) {
	http.Error(w, "not implemented", http.StatusNotImplemented)
}
